In [17]:
import numpy as np



In [18]:
# No. 1
vector = np.linspace(1,10, num=10)
print(vector)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [19]:
# No. 2
zeros_matrix = np.zeros((3, 3), dtype=int)
print(zeros_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
# No. 3
random_no_matrix = np.random.randint(low=1, high=10, size=(5, 5))
print(random_no_matrix)

[[1 6 2 3 6]
 [7 8 9 3 6]
 [1 8 9 2 5]
 [5 8 9 3 9]
 [3 6 1 3 5]]


In [21]:
# No. 4
random_real_no = np.random.rand(4, 4)
print(random_real_no)

[[0.36704505 0.68202388 0.00395755 0.32153122]
 [0.45285901 0.19335285 0.26802289 0.27542949]
 [0.84021373 0.60276692 0.05636964 0.40776619]
 [0.83651281 0.449728   0.07018752 0.44040649]]


In [22]:
# No. 5
random_a_vector = np.random.randint(low=1, high=10, size=(1, 5))
random_b_vector = np.random.randint(low=1, high=10, size=(1, 5))

print("Random A: ", random_a_vector)
print("Random B: ",random_b_vector)

add = random_a_vector + random_b_vector
print("Add: ", add)

subtract = random_a_vector - random_b_vector
print("Subtract: ", subtract)

multiply = random_a_vector * random_b_vector
print("Multiply: ", multiply)

Random A:  [[9 2 2 7 8]]
Random B:  [[3 7 7 7 1]]
Add:  [[12  9  9 14  9]]
Subtract:  [[ 6 -5 -5  0  7]]
Multiply:  [[27 14 14 49  8]]


In [23]:
# No. 6
random_a2_vector = np.random.random(size=(1, 7))
random_b2_vector = np.random.random(size=(1, 7))

print("Random A2: ", random_a2_vector)
print("Random B2: ",random_b2_vector)

multiply2 = random_a2_vector * random_b2_vector
print("Multiply2: ", multiply2)

Random A2:  [[0.4905114  0.71122396 0.0109757  0.46728291 0.32978062 0.93867897
  0.84710853]]
Random B2:  [[0.45541952 0.86407286 0.03519623 0.16775263 0.91888379 0.63918052
  0.81746369]]
Multiply2:  [[2.23388465e-01 6.14549327e-01 3.86303369e-04 7.83879367e-02
  3.03030065e-01 5.99985311e-01 6.92480467e-01]]


In [25]:
# No. 7
random_A_matrix = np.random.randint(low=1, high=10, size=(2, 2))
random_B_matrix = np.random.randint(low=1, high=10, size=(2, 3))
print("Rand A Matrix: ",random_A_matrix)
print("Rand B Matrix: ",random_B_matrix)

mul_matrixes = np.dot(random_A_matrix, random_B_matrix)

print("Mul Matrixes: ", mul_matrixes)

Rand A Matrix:  [[4 7]
 [3 5]]
Rand B Matrix:  [[3 1 1]
 [6 7 1]]
Mul matrixes:  [[54 53 11]
 [39 38  8]]


In [32]:
# No. 8
rand_matrix_3x3 = np.random.randint(low=1, high=10, size=(3, 3))
print("Rand_matrix_3x3: ", rand_matrix_3x3)

matrix_inv = np.linalg.inv(rand_matrix_3x3)
print("Inverter matrix: ", matrix_inv)

Rand_matrix_3x3:  [[5 2 9]
 [1 7 9]
 [5 6 7]]
Inverter matrix:  [[ 0.02380952 -0.19047619  0.21428571]
 [-0.18095238  0.04761905  0.17142857]
 [ 0.13809524  0.0952381  -0.15714286]]


In [29]:
# No. 9
rand_matrix_4x4 = np.random.random(size=(4, 4))
print("Rand_matrix_4x4: ", rand_matrix_4x4)

transpose_matrix_4x4 = rand_matrix_4x4.T
print("Transposed matrix: ", transpose_matrix_4x4)

Rand_matrix_4x4:  [[0.57859881 0.89012776 0.25381519 0.73866953]
 [0.74191783 0.63578717 0.58552167 0.46870055]
 [0.61497997 0.71282624 0.44436393 0.76626661]
 [0.96082504 0.52805233 0.0313525  0.15441751]]
Transposed matrix:  [[0.57859881 0.74191783 0.61497997 0.96082504]
 [0.89012776 0.63578717 0.71282624 0.52805233]
 [0.25381519 0.58552167 0.44436393 0.0313525 ]
 [0.73866953 0.46870055 0.76626661 0.15441751]]


In [42]:
# No. 10
rand_matrix_3x4 = np.random.randint(low=1, high=10, size=(3, 4))
rand_vector_4 = np.random.randint(low=1, high=10, size=(1, 4))

print("Rand matrix 3x4: ", rand_matrix_3x4)
print("Rand vector 4: ", rand_vector_4)

rand_vector_4 = rand_vector_4.T

mult_matrix_vector = np.dot(rand_matrix_3x4, rand_vector_4)
print("Matrix multiplied by vector: ", mult_matrix_vector)

Rand matrix 3x4:  [[9 5 9 3]
 [4 2 3 6]
 [4 8 3 3]]
Rand vector 4:  [[3 8 1 4]]
Matrix multiplied by vector:  [[88]
 [55]
 [91]]


In [43]:
# No. 11
rand_matrix_2x3 = np.random.random(size=(2, 3))
rand_vector_3 = np.random.random(size=(1, 3))

print("Rand matrix 2x3: ", rand_matrix_2x3)
print("Rand vector 3: ", rand_vector_3)

rand_vector_3 = rand_vector_3.T

mult_matrix_vector2 = np.dot(rand_matrix_2x3, rand_vector_3)
print("Matrix multiplied by vector: ", mult_matrix_vector2)

Rand matrix 2x3:  [[0.74570173 0.97161989 0.46778639]
 [0.85114949 0.30777476 0.88139026]]
Rand vector 3:  [[0.6168549  0.99625994 0.45641342]]
Matrix multiplied by vector:  [[1.64147974]
 [1.23393775]]


In [80]:
# No. 12
first_random_matrix_2x2 = np.random.randint(low=1, high=10, size=(2, 2))
second_random_matrix_2x2 = np.random.randint(low=1, high=10, size=(2, 2))

print("First: ", first_random_matrix_2x2)
print("Second: ", second_random_matrix_2x2)

element_wise_mul_matrix = np.multiply(first_random_matrix_2x2, second_random_matrix_2x2)
print("Element-wise multiplied matrix: ", element_wise_mul_matrix)

First:  [[1 1]
 [8 1]]
Second:  [[6 6]
 [7 8]]
Element-wise multiplied matrix:  [[ 6  6]
 [56  8]]


In [44]:
# No. 13
first_random_matrix_2x2 = np.random.randint(low=1, high=10, size=(2, 2))
second_random_matrix_2x2 = np.random.randint(low=1, high=10, size=(2, 2))

print("First: ", first_random_matrix_2x2)
print("Second: ", second_random_matrix_2x2)

mul_matrix = np.dot(first_random_matrix_2x2, second_random_matrix_2x2)
print("Multiplied matrix: ", mul_matrix)

First:  [[4 2]
 [7 8]]
Second:  [[2 2]
 [8 4]]
Multiplied matrix:  [[24 16]
 [78 46]]


In [45]:
# No. 14
rand_100_matrix = np.random.randint(low=1, high=100, size=(5, 5))
print("Random 100 matrix: ", rand_100_matrix)

sum_matrix_100 = rand_100_matrix.sum()
print("Sum of 100 matrix: ", sum_matrix_100)


Random 100 matrix:  [[52 53 33 56 32]
 [45 20 27 67 36]
 [68 39 59 63 40]
 [97 46 93 85 74]
 [ 6 33 31 49 90]]
Sum of 100 matrix:  1294


In [46]:
# No. 15
first_random_matrix_4x4 = np.random.randint(low=1, high=10, size=(4, 4))
second_random_matrix_4x4 = np.random.randint(low=1, high=10, size=(4, 4))

print("First: ", first_random_matrix_4x4)
print("Second: ", second_random_matrix_4x4)

subtract_matrix = np.subtract(first_random_matrix_4x4, second_random_matrix_4x4)
print("Subtract: ", subtract_matrix)

First:  [[6 9 6 8]
 [8 4 8 8]
 [1 9 1 8]
 [7 6 3 1]]
Second:  [[4 6 8 1]
 [5 6 9 3]
 [3 8 3 1]
 [1 9 7 4]]
Subtract:  [[ 2  3 -2  7]
 [ 3 -2 -1  5]
 [-2  1 -2  7]
 [ 6 -3 -4 -3]]


In [55]:
# No. 16

rand_matrix_3x3 = np.random.random(size=(3, 3))
print("Rand 3x3 matrix: ", rand_matrix_3x3)

vector_of_rows_sum = np.sum(rand_matrix_3x3, axis=1)
vector_of_rows_sum = vector_of_rows_sum.T
print("Vector: ", vector_of_rows_sum, "shape: ", vector_of_rows_sum.shape)

Rand 3x3 matrix:  [[0.46178813 0.82923703 0.64343194]
 [0.82525754 0.62162211 0.55706128]
 [0.81791985 0.54334867 0.34523167]]
Vector:  [1.9344571  2.00394094 1.70650019] shape:  (3,)


In [63]:
# No. 17
rand_3x4_matrix = np.random.randint(low=1, high=10, size=(3, 4))
print("Matrix: ", rand_3x4_matrix)

square_matrix = np.square(rand_3x4_matrix)
print("Square matrix: ", square_matrix)

Matrix:  [[4 5 5 6]
 [7 4 9 5]
 [2 1 5 7]]
Sqr matrix:  [[16 25 25 36]
 [49 16 81 25]
 [ 4  1 25 49]]


In [78]:
# No. 18
random_4_vector = np.random.randint(low=1, high=10, size=(1, 4), dtype=int)
print("Random 4 vector: ", random_4_vector)

sqrt_vector = np.sqrt(random_4_vector)
print("Square-root vector: ", sqrt_vector)

Random 4 vector:  [[1 8 6 9]]
Square-root vector:  [[1.         2.82842712 2.44948974 3.        ]]
